[book]
authors = ["Mike Burns"]
language = "en"
multilingual = false
src = "src"
title = "factory_bot"

[output.html.redirect]
"/setup/rspec.html" = "https://github.com/thoughtbot/factory_bot/wiki/Integration:-RSpec"
"/setup/cucumber.html" = "https://github.com/thoughtbot/factory_bot/wiki/Integration:-Cucumber"
"/setup/minitest-rails.html" = "https://github.com/thoughtbot/factory_bot/wiki/Integration:-minitest-rails"
"/setup/minitest-spec.html" = "https://github.com/thoughtbot/factory_bot/wiki/Integration:-Minitest::Spec"
"/setup/minitest.html" = "https://github.com/thoughtbot/factory_bot/wiki/Integration:-Minitest"
"/setup/spinach.html" = "https://github.com/thoughtbot/factory_bot/wiki/Integration:-Spinach"
"/setup/test-unit.html" = "https://github.com/thoughtbot/factory_bot/wiki/Integration:-Test::Unit"
"/setup/update-gemfile.html" = "summary.html"
"/setup/configure-test-suite.html" = "summary.html"
"/using-factories/build_stubbed-and-marshaldump.html" = "build-strategies.html"
"/associations/has_many-associations.html" = "../cookbook/has_many-associations.html"
"/associations/has_and_belongs_to_many-associations.html" = "../cookbook/has_and_belongs_to_many-associations.html"
"/associations/polymorphic-associations.html" = "../cookbook/polymorphic-associations.html"
"/associations/interconnected-associations.html" = "../cookbook/interconnected-associations.html"
"/traits/defining-traits.html" = "summary.html"
"/callbacks/default-callbacks.html" = "summary.html"
