name: Build
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - jruby-9.4
          - truffleruby
          - "3.4"
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
        rails:
          - "6.1"
          - "7.0"
          - "7.1"
          - "7.2"
          - main
        exclude:
          - { ruby: jruby-9.4, rails: "7.1" }
          - { ruby: jruby-9.4, rails: "7.2" }
          - { ruby: jruby-9.4, rails: main }
          # Rails >= 7.2 requires Ruby 3.1
          - { ruby: "3.0", rails: "7.2" }
          - { ruby: "3.0", rails: "main" }
          # Rails >= 8.0 requires Ruby 3.2
          - { ruby: "3.1", rails: "main" }
          # 2025-10-23 There's an incompatibility between truffleruby and rails edge Git ref
          # results in a "NoMethodError: undefined method `[]' for class Fiber" error whilst running specs
          - { ruby: truffleruby, rails: "main" }

    runs-on: 'ubuntu-latest'

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile

    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup project
        run: bundle install
      - name: Run test
        run: bundle exec rake all_specs

  standard:
    name: Run standard
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - name: Setup project
        run: bundle install
      - name: Run test
        run: bundle exec rake standard
