name: Build
on:
  - push
  - pull_request

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - jruby-9.2.16.0
          - truffleruby
          - "3.1"
          - "3.0"
          - "2.7"
          - "2.6"
          - "2.5"
        rails:
          - "5.0"
          - "5.1"
          - "5.2"
          - "6.0"
          - "6.1"
          - "7.0"
          - main
        exclude:
          - ruby: 2.5
            rails: "7.0"
          - ruby: 2.5
            rails: main
          - ruby: 2.6
            rails: "7.0"
          - ruby: 2.6
            rails: main
          - ruby: jruby-9.2.16.0
            rails: "7.0"
          - ruby: jruby-9.2.16.0
            rails: main
          - ruby: "3.0"
            rails: "5.0"
          - ruby: "3.0"
            rails: "5.1"
          - ruby: "3.0"
            rails: "5.2"
          - ruby: truffleruby
            rails: "5.0"
          - ruby: truffleruby
            rails: "5.1"
          - ruby: truffleruby
            rails: "5.2"
          - ruby: "3.1"
            rails: "5.0"
          - ruby: "3.1"
            rails: "5.1"
          - ruby: "3.1"
            rails: "5.2"
          - ruby: "3.1"
            rails: "6.0"

    runs-on: 'ubuntu-latest'

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile
      RUBYOPT: "--disable-error_highlight"

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup project
        run: bundle install
      - name: Run test
        run: bundle exec rake all_specs

  standard:
    name: Run standard
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Setup project
        run: bundle install
      - name: Run test
        run: bundle exec rake standard
